services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai_girlfriend}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - HF_API_KEY=${HF_API_KEY}
      - HF_MODEL_NAME=${HF_MODEL_NAME:-bartowski/L3-TheSpice-8b-v0.8.3-GGUF}
      - HF_MAX_TOKENS=${HF_MAX_TOKENS:-512}
      - HF_TEMPERATURE=${HF_TEMPERATURE:-1.2}
      - HF_TOP_P=${HF_TOP_P:-0.75}
      - HF_REPETITION_PENALTY=${HF_REPETITION_PENALTY:-1.25}
      - HF_TIMEOUT=${HF_TIMEOUT:-30}
      - HF_MAX_RETRIES=${HF_MAX_RETRIES:-3}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-ai_girlfriend}
      - REDIS_URL=redis://redis:6379/0
      - SCHEDULE_TIMEZONE=Europe/Kyiv
      - FREE_DAILY_LOANS=10
      - RATE_LIMIT_PER_USER_SEC=3
      - HF_MAX_RPS=5
      - LAVA_API_KEY=${LAVA_API_KEY}
      - LAVA_SHOP_ID=${LAVA_SHOP_ID}
      - LAVA_WEBHOOK_SECRET=${LAVA_WEBHOOK_SECRET}
      - LAVA_WEBHOOK_URL=${LAVA_WEBHOOK_URL}
      - BOT_NAME=${BOT_NAME:-ai-girlfriend}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./app:/app/app  # Mount to correct location for development
      - ./tests:/app/tests  # Mount tests directory
    ports:
      - "8000:8000"
    command: python -m bot

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-ai_girlfriend}
      - REDIS_URL=redis://redis:6379/0
      - LAVA_API_KEY=${LAVA_API_KEY}
      - LAVA_SHOP_ID=${LAVA_SHOP_ID}
      - LAVA_WEBHOOK_SECRET=${LAVA_WEBHOOK_SECRET}
      - LAVA_WEBHOOK_URL=${LAVA_WEBHOOK_URL}
      - BOT_NAME=${BOT_NAME:-ai-girlfriend}
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - WEBHOOK_MODE=true
    volumes:
      - ./app:/app/app  # Mount to correct location for development
    ports:
      - "8001:8001"
    command: uvicorn app.webhook.handler:app --host 0.0.0.0 --port 8001

volumes:
  postgres_data: 